/-
  VicoEnum/Build.lean

  Building a frieze from a quiddity.

  `entry_eq_continuant` runs one way: a frieze's entries are continuants of its quiddity.
  The converse of Proposition `prop:w5cond` needs the other way, and this file supplies the
  general machinery for it. Setting

      friezeOf a (r+1) j = K_r(a_j, …, a_{j+r-1}),      friezeOf a 0 j = 0,

  the diamond rule is automatic: it is exactly `Kc_identity`, so nothing about the quiddity
  is needed for it. What remains is periodicity, which follows from periodicity of `a`, and
  the two closing conditions `K_{n-2} = 1` and `K_{n-1} = 0`, which are conditions on `a`
  and are where the arithmetic of the width lives.

  This reduces "build a frieze of width `n`" to "check two continuant identities", which at
  width 5 is a finite computation in the quiddity entries.
-/
import VicoEnum.Frieze

namespace VicoEnum

/-- The array generated by a quiddity: row `r+1` is the continuant of the length-`r` window
starting at the column, and row `0` vanishes. -/
def friezeOf (a : ℤ → ℚ) : ℕ → ℤ → ℚ
  | 0, _ => 0
  | (r + 1), j => Kc a j r

@[simp] theorem friezeOf_zero (a : ℤ → ℚ) (j : ℤ) : friezeOf a 0 j = 0 := rfl
@[simp] theorem friezeOf_one (a : ℤ → ℚ) (j : ℤ) : friezeOf a 1 j = 1 := rfl
@[simp] theorem friezeOf_two (a : ℤ → ℚ) (j : ℤ) : friezeOf a 2 j = a j := rfl

theorem friezeOf_succ (a : ℤ → ℚ) (r : ℕ) (j : ℤ) :
    friezeOf a (r + 1) j = Kc a j r := rfl

/-- **The diamond rule is automatic.** It is `Kc_identity`, and holds for every `a`. -/
theorem friezeOf_diamond (a : ℤ → ℚ) (r : ℕ) (j : ℤ) (h2 : 2 ≤ r) :
    friezeOf a (r - 2) (j + 1) * friezeOf a r j
      = friezeOf a (r - 1) j * friezeOf a (r - 1) (j + 1) - 1 := by
  match r, h2 with
  | 2, _ => simp
  | (k + 3), _ =>
    show friezeOf a (k + 1) (j + 1) * friezeOf a (k + 3) j
      = friezeOf a (k + 2) j * friezeOf a (k + 2) (j + 1) - 1
    rw [friezeOf_succ, friezeOf_succ, friezeOf_succ, friezeOf_succ]
    have := Kc_identity a j k
    linarith [this]

/-- Periodicity of the quiddity passes to the continuants. -/
theorem Kc_periodic {a : ℤ → ℚ} {n : ℤ} (hper : ∀ j, a (j + n) = a j) (j : ℤ) :
    ∀ k, Kc a (j + n) k = Kc a j k := by
  intro k
  induction k using Nat.strong_induction_on with
  | _ k ih =>
    match k with
    | 0 => rfl
    | 1 => simpa using hper j
    | (p + 2) =>
      rw [Kc_succ_succ, Kc_succ_succ, ih (p + 1) (by omega), ih p (by omega)]
      congr 1
      have : j + n + (p : ℤ) + 1 = (j + p + 1) + n := by ring
      rw [this, hper]

/-- **Building a frieze.** A periodic quiddity satisfying the two closing conditions
generates a frieze of width `n`. -/
theorem friezeOf_isFrieze {n : ℕ} {a : ℤ → ℚ} (hn : 3 ≤ n)
    (hper : ∀ j : ℤ, a (j + (n : ℤ)) = a j)
    (htop : ∀ j : ℤ, Kc a j (n - 2) = 1) (hzero : ∀ j : ℤ, Kc a j (n - 1) = 0) :
    IsFrieze n (friezeOf a) where
  periodic := by
    intro r j
    match r with
    | 0 => rfl
    | (k + 1) => exact Kc_periodic hper j k
  row_zero := fun j => rfl
  row_one := fun j => rfl
  row_top_one := by
    intro j
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 2 := ⟨n - 2, by omega⟩
    show friezeOf a (m + 2 - 1) j = 1
    have h1 : m + 2 - 1 = m + 1 := by omega
    rw [h1, friezeOf_succ]
    have h := htop j
    have h2 : m + 2 - 2 = m := by omega
    rwa [h2] at h
  row_top_zero := by
    intro j
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 2 := ⟨n - 2, by omega⟩
    show friezeOf a (m + 2) j = 0
    rw [friezeOf_succ]
    have h := hzero j
    have h2 : m + 2 - 1 = m + 1 := by omega
    rwa [h2] at h
  diamond := fun r j h2 _ => friezeOf_diamond a r j h2

end VicoEnum
