"""The subsemigroup vanishing criterion for the fibres of the width-5 count at a prime.

Reducing mod a, the divisors of ap+1 land in the multiplicative subsemigroup of (Z/a)^*
generated by the prime factors of ap+1. So the fibre with leading coefficient a is empty
unless -1 lies in that subsemigroup. The criterion is necessary, costs no analysis, and is
formalised in the special case of Proposition prop:vanish (VicoEnum/ShiftDecomp.lean).

This script measures how much of the vanishing it accounts for, with a running over
1..(2p)^(1/3) and p sampled over four decades. Every loop is capped.

Result: the criterion never fails, and kills 28.6, 31.7, 31.4, 33.1 per cent of all a at
p ~ 1e4, 1e5, 1e6, 1e7. The fraction does not grow, so it improves the constant in
C(p) << p^(1/3+eps) and not the exponent.
"""
import math, random, sys

def is_prime(n):
    if n < 2: return False
    for q in (2,3,5,7,11,13,17,19,23,29,31,37):
        if n % q == 0: return n == q
    d, s = n-1, 0
    while d % 2 == 0: d //= 2; s += 1
    for q in (2,3,5,7,11,13,17,19,23,29,31,37):
        x = pow(q, d, n)
        if x in (1, n-1): continue
        for _ in range(s-1):
            x = x*x % n
            if x == n-1: break
        else: return False
    return True

def _rho(n):
    if n % 2 == 0: return 2
    while True:
        x = random.randrange(2, n); y = x; c = random.randrange(1, n); d = 1
        while d == 1:
            x = (x*x+c) % n; y = (y*y+c) % n; y = (y*y+c) % n
            d = math.gcd(abs(x-y), n)
        if d != n: return d

def factor(n, out=None):
    out = {} if out is None else out
    if n == 1: return out
    if is_prime(n): out[n] = out.get(n, 0) + 1; return out
    d = _rho(n); factor(d, out); factor(n//d, out); return out

def divisors(f):
    ds = [1]
    for q, e in f.items():
        ds = [d * q**i for d in ds for i in range(e+1)]
    return ds

def subsemigroup_has_neg_one(gens, a):
    """Is -1 in the subsemigroup of (Z/a)^* generated by gens?  Closure is capped by a."""
    if a <= 2: return True
    gens = [g % a for g in gens if math.gcd(g, a) == 1]
    seen = {1}; frontier = [1]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = x*g % a
                if y not in seen: seen.add(y); nxt.append(y)
        frontier = nxt
        if len(seen) >= a: break
    return (a-1) % a in seen

def sweep(seed=11):
    random.seed(seed)
    print("     p scale     a up to    pairs   fibres>0   zeros   proved zero"
          "   killed/all   violations")
    for lo, hi, cnt in [(10**4, 3*10**4, 12), (10**5, 3*10**5, 12),
                        (10**6, 3*10**6, 10), (10**7, 3*10**7, 8)]:
        pairs = zeros = proved = pos = viol = 0; A = 0
        for _ in range(cnt):
            p = random.randrange(lo, hi) | 1
            while not is_prime(p): p += 2
            A = int((2*p) ** (1/3))
            for a in range(1, A+1):
                f = factor(a*p + 1)
                r = sum(1 for D in divisors(f) if (D+1) % a == 0)
                ok = subsemigroup_has_neg_one(list(f), a)
                pairs += 1
                if r > 0:
                    pos += 1
                    if not ok: viol += 1     # would refute the criterion
                else:
                    zeros += 1
                    if not ok: proved += 1
        print(f"  {lo:>9}      {A:>5}   {pairs:>6}   {pos:>8}  {zeros:>6}   {proved:>9}"
              f"       {100*proved/pairs:5.1f}%   {viol:>10}")

if __name__ == "__main__":
    sweep(int(sys.argv[1]) if len(sys.argv) > 1 else 11)
